service: picus_delete
frameworkVersion: ^3.22.0

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 256
  timeout: 60
  architecture: arm64
  iam:
    role:
      statements:
        -   Effect: "Allow"
            Action:
              - "dynamodb:DeleteItem"
            Resource:
              - "${self:functions.delete.environment.DYNAMODB_TABLE_ARN}"
functions:
  delete:
    name: ${self:service}
    handler: delete.handler
    events:
      - httpApi:
          path: /picus/{key}
          method: delete
    environment:
      DYNAMODB_TABLE_ARN: "arn:aws:dynamodb:us-east-1:152547606290:table/picus"
